import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { SaasAuthService } from '../services/saas-auth.service';

@Component({
  selector: 'app-saas-shell', standalone: true, imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `<div class="saas-shell"><header class="saas-topbar"><button class="menu" type="button" (click)="menuOpen = !menuOpen" [attr.aria-expanded]="menuOpen" aria-label="Abrir navegación">☰</button><a routerLink="/saas" class="brand"><span class="brand-mark">S</span><span>PLATAFORMA SAAS</span></a><div class="top-actions"><span class="context">Administrador de plataforma</span><button class="logout" type="button" (click)="auth.logout()">Cerrar sesión</button></div></header><div class="saas-body"><aside class="sidebar" [class.open]="menuOpen"><p class="eyebrow">Control central</p><nav aria-label="Navegación SaaS"><a routerLink="/saas" [routerLinkActiveOptions]="{exact:true}" routerLinkActive="active" (click)="menuOpen=false">Resumen</a><a routerLink="/saas/empresas" routerLinkActive="active" (click)="menuOpen=false">Empresas</a><a routerLink="/saas/planes" routerLinkActive="active" (click)="menuOpen=false">Planes</a><a routerLink="/saas/suscripciones" routerLinkActive="active" (click)="menuOpen=false">Suscripciones</a><a routerLink="/saas/tenants" routerLinkActive="active" (click)="menuOpen=false">Tenants</a><a routerLink="/saas/provisionamientos" routerLinkActive="active" (click)="menuOpen=false">Provisionamientos</a><a routerLink="/saas/bitacora" routerLinkActive="active" (click)="menuOpen=false">Bitácora</a><p class="eyebrow group">Respaldos</p><a routerLink="/saas/backups" routerLinkActive="active" (click)="menuOpen=false">Backups</a><a routerLink="/saas/backup-policies" routerLinkActive="active" (click)="menuOpen=false">Políticas automáticas</a><a routerLink="/saas/restores" routerLinkActive="active" (click)="menuOpen=false">Restauraciones</a></nav><div class="boundary"><strong>PLATAFORMA SAAS</strong><span>Esta consola no es el administrador de una clínica tenant.</span></div></aside><main class="content"><router-outlet /></main></div></div>`,
  styles: [`:host{display:block;min-height:100vh}.saas-shell{min-height:100vh;background:#f5f7fb;color:#172b4d}.saas-topbar{height:72px;background:#102a43;color:#fff;display:flex;align-items:center;padding:0 28px;gap:18px}.brand{display:flex;align-items:center;gap:10px;font-size:.82rem;font-weight:800;letter-spacing:.09em}.brand-mark{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#38bdf8;color:#102a43;font-weight:900}.top-actions{margin-left:auto;display:flex;align-items:center;gap:20px}.context{font-size:.82rem;color:#c8d9eb}.logout,.menu{border:1px solid #62809d;background:transparent;color:#fff;border-radius:8px;padding:9px 13px;cursor:pointer}.menu{display:none;font-size:1.2rem}.saas-body{display:flex;min-height:calc(100vh - 72px)}.sidebar{width:260px;flex:0 0 260px;padding:28px 18px;background:#fff;border-right:1px solid #e2e8f0;display:flex;flex-direction:column}.eyebrow{margin:0 12px 12px;color:#64748b;font-size:.72rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.sidebar nav{display:grid;gap:4px}.eyebrow.group{margin-top:20px}.sidebar nav a{padding:11px 12px;border-radius:9px;color:#42526e;font-weight:600}.sidebar nav a:hover,.sidebar nav a.active{background:#e8f4ff;color:#1261a0}.boundary{margin-top:auto;border:1px solid #b9def1;background:#f0f9ff;border-radius:12px;padding:14px;font-size:.75rem;color:#35627c}.boundary strong{display:block;color:#1261a0;font-size:.7rem;letter-spacing:.08em;margin-bottom:5px}.content{flex:1;min-width:0;padding:32px;max-width:1600px}.menu:focus-visible,.logout:focus-visible,.sidebar a:focus-visible{outline:3px solid #38bdf8;outline-offset:2px}@media(max-width:820px){.menu{display:block}.context{display:none}.sidebar{position:fixed;z-index:10;top:72px;bottom:0;left:0;transform:translateX(-105%);transition:transform .2s;box-shadow:8px 0 24px #102a4326}.sidebar.open{transform:translateX(0)}.content{padding:24px 18px}}@media(max-width:480px){.saas-topbar{padding:0 14px}.brand{font-size:.7rem}.content{padding:20px 12px}}`],
})
export class SaasShellComponent { readonly auth = inject(SaasAuthService); menuOpen = false; }
