import { CommonModule } from '@angular/common';
import { AfterViewChecked, Component, ElementRef, HostListener, OnInit, ViewChild, computed, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable, finalize } from 'rxjs';
import { Empresa, EmpresaEstado, Suscripcion, SuscripcionEstado } from '../models/saas.models';
import { SaasApiService } from '../services/saas-api.service';

type Kind = 'empresas' | 'planes' | 'suscripciones' | 'tenants' | 'provisionamientos' | 'bitacora';
const titles: Record<Kind, [string, string]> = { empresas: ['Empresas', 'Metadata y estado operativo de cada organización.'], planes: ['Planes', 'Catálogo vigente de planes comerciales.'], suscripciones: ['Suscripciones', 'Estado y vigencia de las suscripciones contratadas.'], tenants: ['Tenants', 'Estado de las bases de datos tenant y su esquema.'], provisionamientos: ['Provisionamientos', 'Seguimiento de procesos de creación y actualización.'], bitacora: ['Bitácora SaaS', 'Trazabilidad de acciones administrativas sin exponer secretos.'] };

@Component({
  selector: 'app-saas-collection', standalone: true, imports: [CommonModule],
  template: `<section class="page" [attr.aria-busy]="loading()"><div class="page-head"><div><p class="eyebrow">PLATAFORMA SAAS</p><h1>{{title}}</h1><p>{{description}}</p></div><button class="refresh" type="button" (click)="load()" [disabled]="loading()">{{loading() ? 'Actualizando…' : 'Actualizar'}}</button></div><p class="status" aria-live="polite" *ngIf="loading()">Cargando {{title.toLowerCase()}}…</p><p class="error" role="alert" aria-live="assertive" *ngIf="error()">{{error()}}</p><div class="table-wrap" *ngIf="!error()"><table><caption class="visually-hidden">{{title}}</caption><thead><tr><th *ngFor="let col of columns">{{col}}</th><th *ngIf="kind === 'empresas' || kind === 'suscripciones'">Acciones</th></tr></thead><tbody><tr *ngFor="let row of rows()"><td *ngFor="let col of columns">{{display(row, col)}}</td><td *ngIf="kind === 'empresas' || kind === 'suscripciones'" class="actions"><button *ngIf="kind === 'suscripciones' || canChangeCompany(row)" type="button" (click)="requestChange(row)">{{kind === 'empresas' ? (row.estado === 'ACTIVA' ? 'Suspender' : 'Activar') : 'Seleccionar estado'}}</button><span class="no-action" *ngIf="kind === 'empresas' && !canChangeCompany(row)">Sin acción disponible</span><button *ngIf="kind === 'empresas'" type="button" class="subtle" (click)="openDetail(row)">Detalle</button></td></tr><tr *ngIf="!loading() && rows().length === 0"><td [attr.colspan]="columns.length + 1" class="empty">No hay registros para mostrar.</td></tr></tbody></table></div><div class="modal-backdrop" *ngIf="detail() || pending()" (click)="closeModal($event)"><section #modal class="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1" (keydown.escape)="closeModal()"><button class="close" type="button" aria-label="Cerrar" (click)="closeModal()">×</button><ng-container *ngIf="detail()"><h2 id="dialog-title">Detalle de empresa</h2><dl><div *ngFor="let col of columns"><dt>{{col}}</dt><dd>{{display(detail(), col)}}</dd></div></dl><button class="primary" type="button" (click)="closeModal()">Cerrar</button></ng-container><ng-container *ngIf="pending()"><h2 id="dialog-title">Confirmar cambio</h2><p>Selecciona explícitamente el estado que deseas enviar.</p><label for="estado-modal">Estado</label><select id="estado-modal" [value]="selectedState()" (change)="selectedState.set($any($event.target).value)"><option *ngFor="let state of statesForPending()" [value]="state">{{state}}</option></select><div class="modal-actions"><button type="button" (click)="closeModal()">Cancelar</button><button class="primary" type="button" (click)="confirmChange()" [disabled]="saving()">{{saving() ? 'Guardando…' : 'Confirmar'}}</button></div></ng-container></section></div></section>`,
  styles: [`:host{display:block}.page{max-width:1500px;margin:auto}.page-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:28px}.eyebrow{margin:0 0 8px;color:#1683b6;text-transform:uppercase;letter-spacing:.1em;font-weight:800;font-size:.72rem}h1{font-size:clamp(1.8rem,4vw,2.5rem);margin:0;color:#102a43}p{color:#64748b}.refresh,.actions button,.modal-actions button{border:1px solid #b8d5e8;background:#fff;color:#1261a0;border-radius:8px;padding:9px 12px;font-weight:700;cursor:pointer}.table-wrap{background:#fff;border:1px solid #e1eaf2;border-radius:14px;overflow:auto}table{width:100%;min-width:900px;border-collapse:collapse;font-size:.83rem}th,td{text-align:left;padding:13px 14px;border-bottom:1px solid #edf2f7;vertical-align:top}th{background:#f7fafc;color:#486581;font-size:.72rem;text-transform:uppercase;white-space:nowrap}td{color:#334e68}.actions{white-space:nowrap}.subtle{margin-left:6px}.no-action{color:#64748b;font-size:.8rem}.empty{text-align:center;padding:40px}.error{color:#be123c;background:#fff1f2;padding:12px;border-radius:8px}.modal-backdrop{position:fixed;inset:0;background:#102a4366;display:grid;place-items:center;padding:18px;z-index:20}.modal{position:relative;width:min(100%,560px);max-height:90vh;overflow:auto;background:#fff;border-radius:14px;padding:28px;box-shadow:0 20px 60px #102a4350}.modal:focus{outline:3px solid #38bdf8;outline-offset:3px}.modal h2{color:#102a43}.close{position:absolute;right:14px;top:10px;background:transparent;border:0;font-size:1.7rem;color:#486581;cursor:pointer}.modal dl{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal dt{font-size:.7rem;color:#64748b;text-transform:uppercase}.modal dd{margin:2px 0;color:#102a43}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.primary{background:#1261a0!important;color:#fff!important}.visually-hidden{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}@media(max-width:600px){.page-head{display:block}.refresh{margin-top:18px;width:100%}}`],
})
export class SaasCollectionComponent implements OnInit, AfterViewChecked {
  private readonly route = inject(ActivatedRoute);
  private readonly api = inject(SaasApiService);
  @ViewChild('modal') private modal?: ElementRef<HTMLElement>;
  readonly kind = this.route.snapshot.data['kind'] as Kind;
  readonly title = titles[this.kind][0]; readonly description = titles[this.kind][1];
  readonly columns = this.kind === 'empresas' ? ['nombre','codigo','slug','estado','plan','estado_suscripcion','estado_tenant','version_schema','fecha_provisionamiento'] : this.kind === 'planes' ? ['id','codigo','nombre','descripcion','precio_mensual','moneda','limite_usuarios','limite_almacenamiento_mb','estado'] : this.kind === 'suscripciones' ? ['id','empresa_id','plan_id','fecha_inicio','fecha_fin','estado'] : this.kind === 'tenants' ? ['empresa','estado','version_schema','fecha_provisionamiento','ultima_verificacion'] : this.kind === 'provisionamientos' ? ['id','empresa_id','tenant_database_id','estado','paso_actual','intentos','fecha_inicio','fecha_fin','mensaje_error'] : ['id','saas_usuario_id','fecha_hora','ip','accion','entidad_afectada','id_registro_afectado','descripcion','resultado'];
  readonly companyStates: EmpresaEstado[] = ['ACTIVA', 'SUSPENDIDA']; readonly subscriptionStates: SuscripcionEstado[] = ['PENDIENTE', 'ACTIVA', 'SUSPENDIDA', 'VENCIDA', 'CANCELADA'];
  readonly rows = signal<any[]>([]); readonly loading = signal(false); readonly error = signal(''); readonly detail = signal<Empresa | null>(null); readonly pending = signal<(Empresa | Suscripcion) | null>(null); readonly saving = signal(false); readonly selectedState = signal<SuscripcionEstado>('ACTIVA');
  readonly statesForPending = computed<readonly (EmpresaEstado | SuscripcionEstado)[]>(() => this.kind === 'empresas' ? this.companyStates : this.subscriptionStates);
  private focusModal = false;

  ngOnInit(): void { this.load(); }
  ngAfterViewChecked(): void { if (this.focusModal && this.modal) { this.focusModal = false; this.modal.nativeElement.focus(); } }
  @HostListener('document:keydown.escape') handleEscape(): void { if (this.detail() || this.pending()) this.closeModal(); }
  private request(): Observable<unknown[]> { switch (this.kind) { case 'empresas': return this.api.empresas(); case 'planes': return this.api.planes(); case 'suscripciones': return this.api.suscripciones(); case 'tenants': return this.api.tenants(); case 'provisionamientos': return this.api.provisionamientos(); default: return this.api.bitacora(); } }
  load(): void { this.loading.set(true); this.error.set(''); this.request().pipe(finalize(() => this.loading.set(false))).subscribe({ next: (rows) => this.rows.set(rows), error: () => this.error.set('No se pudo cargar la información solicitada.') }); }
  display(row: any, col: string): string { const value = row?.[col]; if (col === 'mensaje_error' && value) return this.safeError(String(value)); return value === null || value === undefined || value === '' ? '—' : String(value); }
  private safeError(value: string): string { const collapsed = value.replace(/[\r\n]+/g, ' ').trim(); const suspicious = /(?:Traceback|Exception|Stack trace|:\/\/|password|passwd|secret|token|api[_-]?key|database_name|storage_key|[A-Za-z]:\\|\/(?:var|home|tmp|usr|etc|app)\/)/i.test(collapsed); if (suspicious || !/^(?:Backup|Restore|Pre-restore|Rollback|Tenant|Company|Manual|Automatic)\b/i.test(collapsed)) return 'La operación reportó un error.'; return collapsed.slice(0, 180); }
  canChangeCompany(row: Empresa): boolean { return row.estado === 'ACTIVA' || row.estado === 'SUSPENDIDA'; }
  requestChange(row: Empresa | Suscripcion): void { if (this.kind === 'empresas' && !this.canChangeCompany(row as Empresa)) return; this.pending.set(row); this.selectedState.set(this.kind === 'empresas' ? ((row as Empresa).estado === 'ACTIVA' ? 'SUSPENDIDA' : 'ACTIVA') : (row as Suscripcion).estado); this.focusModal = true; }
  openDetail(row: Empresa): void { this.detail.set(row); this.focusModal = true; }
  closeModal(event?: Event): void { if (!event || event.target === event.currentTarget) { this.detail.set(null); this.pending.set(null); } }
  confirmChange(): void { const row = this.pending(); if (!row) return; const state = this.selectedState(); if (this.kind === 'empresas' && !this.canChangeCompany(row as Empresa)) return; this.saving.set(true); const call: Observable<unknown> = this.kind === 'empresas' ? this.api.cambiarEmpresaEstado(row.id, state as EmpresaEstado) : this.api.cambiarSuscripcionEstado(row.id, state); call.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.closeModal(); this.load(); }, error: () => this.error.set('No se pudo cambiar el estado. Intenta nuevamente.') }); }
}
